[package]
name = "aist_land_dem_batch_downloader"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.86"
image = {version="0.25.2", features=["png"]}
isahc = "1.7.2"
memmap2 = "0.9.4"
mpi = {version="0.8.0", optional=true}

[features]
mpi = ["dep:mpi"]
